services:
  - type: web
    name: nutri-time-backend
    runtime: node
    buildCommand: npm install --include=dev && npm run build
    startCommand: node --max-old-space-size=400 dist/main
    envVars:
      - key: NODE_ENV
        value: production
